#!/bin/bash

# Define stuff
usage() {
    echo "Usage: ./rcw-cli <command> <flags/arguments>"
    echo
    echo "Available commands:"
    echo "   generate-string-session      Generate an string session to deploy the code to Heroku."
    echo "   start                        Checks your configuration on the fly and then starts up.
    echo "   force-start                  Force start up the userbot without any configuration checks."
    echo "   heroku                       Checks for any cofnig vars, then launch the userbot. Recommended for Heroku users."
    echo "   help                         Show this help message."
    echo "   docs                         Get the link to the documentation."
}

if [[ $1 == "generate-string-session" ]]
then
    echo "[INFO] Opening the script..."
    python3 stringSessionGenerator.py
elif [[ $1 == "force-start" ]]
then
    echo "[INFO] Starting up..."
    python3 -m Sibyl_System
elif [[ $1 == "heroku" ]]
then
    echo "[INFO] Checking your configuration..."
    sleep 5
    if [[ $ENV == "True" || $ENV == "ANYTHING" ]]
    then
        echo "[INFO] Using config vars instead of config file, verifying config..."
        sleep 5
        if [[ $STRING_SESSION == "" ]]
        then
            echo "error:    Your string session is blank."
            echo "error:    Please generate one with the 'generate-string-session' command."
            exit 1
        fi
        echo "[INFO] Starting up in 3..."
        sleep 1
        echo "[INFO] Starting up in 2..."
        sleep 1
        echo "[INFO] Starting up in 1..."
        sleep 1
        echo "[INFO] Starting up, REEEEEEEEEEE..."
        python3 -m Sibyl_System
    else
        echo "error:    Cannot start the bot without required vars: ENV"
        echo "error:    To continue, set it to 'True' or 'ANYTHING'."
    fi
    
elif [[ $1 == "help" ]]
then
    usage
elif [[ $1 == "-h" ]]
then
    usage
elif [[ $1 == "--help" ]]
then
    usage
elif [[ $1 == "" ]]
then
    echo "rcw-cli: Version 0.1.0"
    echo "rcw-cli: An basic CLI for Retarded Cases Watcher userbot."
    echo "rcw-cli:"
    echo "rcw-cli: To learn more how to use me, see the 'help' command."
else
    echo "error:    That command doesn't understand by the CLI yet."
    echo "error:    See '$0 help' for list of available commands."
fi
